import {TagType} from "../../types/common";

export const tagList: TagType[] = [
    {id: 1, tagName: "가족"},
    {id: 2, tagName: "우정"},
    {id: 3, tagName: "감사"},
    {id: 4, tagName: "존경"},
    {id: 5, tagName: "행복"},
    {id: 6, tagName: "재미"},
    {id: 7, tagName: "자존감"},
    {id: 8, tagName: "희망찬"},
    {id: 9, tagName: "사랑"},
    {id: 10, tagName: "따뜻함"},
    {id: 11, tagName: "평온함"},
    {id: 12, tagName: "흥미진진"},
    {id: 13, tagName: "열정적"},
    {id: 14, tagName: "감동적"},
    {id: 15, tagName: "슬픔"},
    {id: 16, tagName: "화남"},
    {id: 17, tagName: "우울함"},
    {id: 18, tagName: "짜증남"},
    {id: 19, tagName: "절망적"},
    {id: 20, tagName: "혐오"},
    {id: 21, tagName: "어려움"},
    {id: 22, tagName: "19금"},
    {id: 23, tagName: "흥분됨"},
    {id: 24, tagName: "반전"},
    {id: 25, tagName: "공포"},
    {id: 26, tagName: "어두운"},
    {id: 27, tagName: "잔인한"},
    {id: 28, tagName: "유치한"},
    {id: 29, tagName: "지루한"},
    {id: 30, tagName: "더러운"},
]
